import React from "react";

const Assets = {
    images : {
        logo : require('../assets/images/logo.png'),
        bannerBg : require('../assets/images/banner-bg.svg'),
        woman : require('../assets/images/woman-img.svg'),
        mobile : require('../assets/images/mobile-img.png'),
        appStrore : require('../assets/images/apple-icon.png'),
        googlePlay : require('../assets/images/playstore.png'),
        foodIcon : require('../assets/images/foodIcon.png'),
        foodIcon2 : require('../assets/images/foodicon-2.jpg'),
        heartIconRed : require('../assets/images/Health_icon_red.png'),
        orgIcon : require('../assets/images/np-building.svg'),
        distanceIcon : require('../assets/images/np_distance.png'),
        healthProIcon : require('../assets/images/helth-pro-icon.png'),
        peopleImage : require('../assets/images/people-2.png'),
        screenImg1 : require('../assets/images/iphon-1.svg'),
        trophy1 : require('../assets/images/trophy.png'),
        companyAward1 : require('../assets/images/company-award-1.png'),
        hill : require('../assets/images/mountains-1.svg'),
        hillSolo : require('../assets/images/mountains-solo.svg'),
        newsIcon : require('../assets/images/news-icon.png'),
        blogIcon : require('../assets/images/blog.png'),
        poscastIcon : require('../assets/images/podcast.png'),
        interviewIcon : require('../assets/images/interview.png'),
        boyHoping : require('../assets/images/boy_hoping.png'),
        boyHoping2 : require('../assets/images/boy-hop-2.svg'),
        girlCycle : require('../assets/images/girl-with-bicycle.svg'),
        tableTick : require('../assets/images/table-tick.svg'),
        testIcon : require('../assets/images/testimonial-icon.svg'),
        pin : require('../assets/images/pin.png'),
        pinkGradBg : require('../assets/images/gradient-background-1.svg'),
        rightHill : require('../assets/images/hill-right.svg'),
        teamImg1 : require('../assets/images/team-img-1.jpg'),
        teamImg2 : require('../assets/images/team-img-2.jpg'),
        teamImg3 : require('../assets/images/team-img-3.jpg'),
        teamImg4 : require('../assets/images/team-img-4.jpg'),
        teamImg5 : require('../assets/images/team-img-5.jpg'),
        teamImg6 : require('../assets/images/team-img-6.jpg'),
        linkedIn : require('../assets/images/linkedin.png'),
        menConversation : require('../assets/images/men-conversation.svg'),
        explainerFunnel : require('../assets/images/explainer-img.svg'),
        manBenchHill : require('../assets/images/man-sitting-on-bench-hill.svg'),
        wrong : require('../assets/images/close.png'),
        right : require('../assets/images/currect.png'),
        manAtDesk : require('../assets/images/man-at-desk.svg'),
    }
}

export default Assets;